class EmojiItem {
  final String emoji;
  final String name;
  final List<String> keywords;

  const EmojiItem(this.emoji, this.name, this.keywords);
}

const List<EmojiItem> emojiDatabase = [
  // Smileys & People
  EmojiItem('😊', 'Gülümseyen', ['mutlu', 'smile', 'happy', 'sevinçli', 'keyifli', 'gülümseme']),
  EmojiItem('😀', 'Sırıtan', ['gülen', 'grin', 'grinning', 'kahkaha', 'neşe']),
  EmojiItem('😂', 'Gözü Yaşlı Gülen', ['kahkaha', 'laugh', 'lol', 'joy', 'komik']),
  EmojiItem('🤣', 'Yerlerde Yuvarlanan', ['rofl', 'laughing', 'kahkaha', 'komik']),
  EmojiItem('😉', 'Göz Kırpan', ['wink', 'göz kırpma', 'şaka']),
  EmojiItem('😍', 'Kalp Gözlü', ['love', 'sevgi', 'aşk', 'beğendim', 'heart eyes']),
  EmojiItem('😘', 'Öpücük Gönderen', ['kiss', 'öpücük', 'aşk', 'love']),
  EmojiItem('🥰', 'Kalpli Gülen', ['sevgi', 'aşk', 'mutlu', 'hearts']),
  EmojiItem('😋', 'Lezzetli', ['yum', 'delicious', 'lezzet', 'yemek', 'tatlı']),
  EmojiItem('😎', 'Gözlüklü', ['cool', 'havalı', 'tarz', 'güneş gözlüğü']),
  EmojiItem('🥳', 'Partileyen', ['party', 'parti', 'kutlama', 'doğum günü', 'eğlence']),
  EmojiItem('🤩', 'Yıldız Gözlü', ['star struck', 'hayran', 'harika', 'yıldız']),
  EmojiItem('😏', 'İmalı', ['smirk', 'alaycı', 'sinsi']),
  EmojiItem('😐', 'Tepkisiz', ['neutral', 'nötr', 'tepkisiz', 'ciddi']),
  EmojiItem('😑', 'İfadesiz', ['expressionless', 'ciddi', 'sıkıcı']),
  EmojiItem('😒', 'Memnuniyetsiz', ['unamused', 'keyifsiz', 'sıkılmış']),
  EmojiItem('🙄', 'Göz Deviren', ['roll eyes', 'bıkkın', 'hıh', 'sıkıcı']),
  EmojiItem('😬', 'Yüzünü Ekşiten', ['grimacing', 'endişeli', 'gergin']),
  EmojiItem('🤥', 'Yalancı', ['lying', 'pinokyo', 'yalan']),
  EmojiItem('😴', 'Uykulu', ['sleep', 'uyku', 'yorgun', 'zzz']),
  EmojiItem('😷', 'Maskeli', ['mask', 'hasta', 'salgın', 'doktor']),
  EmojiItem('🤒', 'Ateşli', ['fever', 'hasta', 'ateş', 'termometre']),
  EmojiItem('🤕', 'Sargılı', ['bandage', 'yaralı', 'kaza', 'baş ağrısı']),
  EmojiItem('🤢', 'Midesi Bulanan', ['nauseated', 'kusma', 'iğrenç', 'yeşil']),
  EmojiItem('🤮', 'Kusan', ['vomit', 'kusma', 'hasta']),
  EmojiItem('🥵', 'Sıcaklamış', ['hot', 'sıcak', 'ateş', 'ter']),
  EmojiItem('🥶', 'Üşümüş', ['cold', 'soğuk', 'dondu', 'buz']),
  EmojiItem('🥴', 'Sarhoş', ['woozy', 'sersem', 'baş dönmesi']),
  EmojiItem('😵', 'Şaşkın Ölü', ['dizzy', 'sersem', 'şaşkın']),
  EmojiItem('🤯', 'Beyni Yanmış', ['mind blown', 'şok', 'şaşırdım', 'patladı']),
  EmojiItem('🤠', 'Kovboy', ['cowboy', 'şapka', 'macera']),
  EmojiItem('😇', 'Melek', ['angel', 'masum', 'temiz']),
  EmojiItem('🤫', 'Şşt', ['shush', 'sessiz', 'sus', 'sır']),
  EmojiItem('🤔', 'Düşünen', ['think', 'düşünce', 'akıl', 'soru']),
  EmojiItem('🧐', 'Monokllü', ['monocle', 'inceleyen', 'araştıran']),
  EmojiItem('😢', 'Üzgün/Ağlamaklı', ['sad', 'cry', 'ağla', 'üzüntü', 'keder']),
  EmojiItem('😭', 'Hıçkıra Hıçkıra Ağlayan', ['sob', 'cry', 'ağla', 'çok üzgün', 'keder']),
  EmojiItem('😡', 'Öfkeli', ['angry', 'kızgın', 'mad', 'öfke', 'kırmızı']),
  EmojiItem('😠', 'Kızgın', ['angry', 'kızgın', 'sinirli']),
  EmojiItem('😱', 'Çığlık Atan', ['scream', 'korku', 'şok', 'şaşırdım']),
  EmojiItem('🥺', 'Yalvaran', ['pleading', 'lütfen', 'kıyamam', 'masum']),
  EmojiItem('😩', 'Bıkkın', ['weary', 'yorgun', 'tükendim']),
  EmojiItem('🥱', 'Esneyen', ['yawn', 'uykulu', 'sıkıcı']),
  EmojiItem('😤', 'Burnundan Soluyan', ['triumph', 'gurur', 'hırs', 'öfkeli']),
  EmojiItem('🤍', 'Beyaz Kalp', ['white heart', 'temiz', 'aşk']),
  EmojiItem('❤️', 'Kırmızı Kalp', ['love', 'heart', 'aşk', 'sevgi', 'kalp']),
  EmojiItem('🧡', 'Turuncu Kalp', ['orange heart', 'dostluk']),
  EmojiItem('💛', 'Sarı Kalp', ['yellow heart', 'arkadaşlık']),
  EmojiItem('💚', 'Yeşil Kalp', ['green heart', 'doğa']),
  EmojiItem('💙', 'Mavi Kalp', ['blue heart', 'huzur']),
  EmojiItem('💜', 'Mor Kalp', ['purple heart', 'asalet']),
  EmojiItem('🖤', 'Siyah Kalp', ['black heart', 'yas', 'karanlık']),
  EmojiItem('🤎', 'Kahverengi Kalp', ['brown heart']),
  EmojiItem('💔', 'Kırık Kalp', ['broken heart', 'ayrılık', 'üzüntü']),
  EmojiItem('❣️', 'Kalpli Ünlem', ['heart exclamation', 'aşk']),
  EmojiItem('💕', 'Çift Kalp', ['two hearts', 'aşk', 'sevgi']),
  EmojiItem('💞', 'Dönen Kalpler', ['revolving hearts', 'aşk']),
  EmojiItem('💓', 'Atan Kalp', ['beating heart', 'heyecan']),
  EmojiItem('💗', 'Büyüyen Kalp', ['growing heart']),
  EmojiItem('💖', 'Işıldayan Kalp', ['sparkling heart']),
  EmojiItem('💘', 'Ok Saplanmış Kalp', ['cupid', 'aşık']),
  EmojiItem('💝', 'Kurdeleli Kalp', ['gift heart', 'hediye']),
  EmojiItem('💟', 'Kalp Süsü', ['heart decoration']),
  EmojiItem('👍', 'Beğeni', ['like', 'thumbs up', 'harika', 'onay', 'yes']),
  EmojiItem('👎', 'Beğenmeme', ['dislike', 'thumbs down', 'red', 'no']),
  EmojiItem('👊', 'Yumruk', ['fist', 'güç', 'tokat']),
  EmojiItem('✊', 'Kalkık Yumruk', ['fist raised', 'direniş', 'güç']),
  EmojiItem('✌️', 'Zafer', ['victory', 'peace', 'barış', 'zafer işareti']),
  EmojiItem('🤞', 'Şans', ['crossed fingers', 'kısmet', 'şans dileme']),
  EmojiItem('🤟', 'Seni Seviyorum', ['love you', 'rock', 'metal']),
  EmojiItem('🤘', 'Rock İşareti', ['horns', 'rock on']),
  EmojiItem('👌', 'Tamam', ['ok', 'okay', 'onay', 'güzel']),
  EmojiItem('👈', 'Sola İşaret', ['point left']),
  EmojiItem('👉', 'Sağa İşaret', ['point right']),
  EmojiItem('👆', 'Yukarı İşaret', ['point up']),
  EmojiItem('👇', 'Aşağı İşaret', ['point down']),
  EmojiItem('☝️', 'Yukarı Tek Parmak', ['point up one']),
  EmojiItem('👋', 'El Sallama', ['wave', 'hello', 'merhaba', 'hoşçakal']),
  EmojiItem('✍️', 'Yazı Yazan El', ['write', 'yazı', 'not', 'kalem']),
  EmojiItem('👏', 'Alkış', ['applause', 'clap', 'tebrik', 'alkışlama']),
  EmojiItem('🙌', 'Yaşasın', ['celebration', 'hooray', 'yaşasın', 'dua']),
  EmojiItem('🙏', 'Dua/Teşekkür', ['pray', 'please', 'thanks', 'teşekkür', 'lütfen', 'dua']),
  EmojiItem('🤝', 'El Sıkışma', ['handshake', 'anlaşma', 'tokalaşma']),
  EmojiItem('💪', 'Güçlü Kol', ['muscle', 'strength', 'güç', 'spor', 'başarı']),
  EmojiItem('🧠', 'Beyin', ['brain', 'akıl', 'zeka', 'düşünce']),
  EmojiItem('👀', 'Gözler', ['eyes', 'bakış', 'dikkat']),

  // Animals & Nature
  EmojiItem('🐶', 'Köpek', ['dog', 'köpek', 'hav', 'pet']),
  EmojiItem('🐱', 'Kedi', ['cat', 'kedi', 'miyav', 'pet']),
  EmojiItem('🐭', 'Fare', ['mouse', 'fare']),
  EmojiItem('🐹', 'Hamster', ['hamster']),
  EmojiItem('🐰', 'Tavşan', ['rabbit', 'bunny', 'tavşan']),
  EmojiItem('🦊', 'Tilki', ['fox', 'tilki']),
  EmojiItem('🐻', 'Ayı', ['bear', 'ayı']),
  EmojiItem('🐼', 'Panda', ['panda']),
  EmojiItem('🐨', 'Koala', ['koala']),
  EmojiItem('🐯', 'Kaplan', ['tiger', 'kaplan']),
  EmojiItem('🦁', 'Aslan', ['lion', 'aslan', 'kral']),
  EmojiItem('🐮', 'İnek', ['cow', 'inek']),
  EmojiItem('🐷', 'Domuz', ['pig', 'domuz']),
  EmojiItem('🐵', 'Maymun', ['monkey', 'maymun']),
  EmojiItem('🐔', 'Tavuk', ['chicken', 'tavuk']),
  EmojiItem('🐧', 'Penguen', ['penguin', 'penguen']),
  EmojiItem('🐦', 'Kuş', ['bird', 'kuş']),
  EmojiItem('🐤', 'Civciv', ['baby chick', 'civciv']),
  EmojiItem('🦆', 'Ördek', ['duck', 'ördek']),
  EmojiItem('🦅', 'Kartal', ['eagle', 'kartal']),
  EmojiItem('🦉', 'Baykuş', ['owl', 'baykuş', 'gece', 'bilge']),
  EmojiItem('🦇', 'Yarasa', ['bat', 'yarasa', 'batman']),
  EmojiItem('🐺', 'Kurt', ['wolf', 'kurt']),
  EmojiItem('🐝', 'Arı', ['bee', 'arı', 'bal', 'çalışkan']),
  EmojiItem('🐛', 'Tırtıl', ['bug', 'tırtıl', 'böcek']),
  EmojiItem('🦋', 'Kelebek', ['butterfly', 'kelebek']),
  EmojiItem('🐌', 'Salyangoz', ['snail', 'salyangoz', 'yavaş']),
  EmojiItem('🐞', 'Uğur Böceği', ['ladybug', 'şans', 'böcek']),
  EmojiItem('🐜', 'Karınca', ['ant', 'karınca', 'çalışkan']),
  EmojiItem('🕷️', 'Örümcek', ['spider', 'örümcek']),
  EmojiItem('🐢', 'Kaplumbağa', ['turtle', 'kaplumbağa', 'yavaş']),
  EmojiItem('🐍', 'Yılan', ['snake', 'yılan']),
  EmojiItem('🐙', 'Ahtapot', ['octopus', 'ahtapot']),
  EmojiItem('🐠', 'Tropikal Balık', ['tropical fish', 'akvaryum']),
  EmojiItem('🐬', 'Yunus', ['dolphin', 'yunus', 'deniz']),
  EmojiItem('🐟', 'Balık', ['fish', 'balık']),
  EmojiItem('🌲', 'Çam Ağacı', ['tree', 'pine', 'çam', 'ağaç', 'orman']),
  EmojiItem('🌳', 'Ağaç', ['deciduous tree', 'ağaç', 'doğa']),
  EmojiItem('🌴', 'Palmiye', ['palm tree', 'palmiye', 'yaz', 'tatil']),
  EmojiItem('🌵', 'Kaktüs', ['cactus', 'kaktüs', 'çöl']),
  EmojiItem('🌱', 'Filiz', ['sprout', 'filiz', 'büyüme', 'doğa']),
  EmojiItem('🍀', 'Dört Yapraklı Yonca', ['clover', 'şans', 'yonca']),
  EmojiItem('🍁', 'Akçaağaç Yaprağı', ['maple leaf', 'sonbahar', 'yaprak']),
  EmojiItem('🌸', 'Kiraz Çiçeği', ['cherry blossom', 'çiçek', 'bahar']),
  EmojiItem('🌹', 'Gül', ['rose', 'gül', 'çiçek', 'aşk']),
  EmojiItem('🌻', 'Ayçiçeği', ['sunflower', 'güneş', 'çiçek']),
  EmojiItem('🌺', 'Hibiskus', ['hibiscus', 'çiçek']),
  EmojiItem('🌷', 'Lale', ['tulip', 'lale', 'çiçek']),
  EmojiItem('🌼', 'Papatya', ['blossom', 'çiçek']),
  EmojiItem('🍄', 'Mantar', ['mushroom', 'mantar']),
  EmojiItem('🔥', 'Ateş', ['fire', 'ateş', 'sıcak', 'popüler', 'harika']),
  EmojiItem('💧', 'Damla', ['droplet', 'su', 'yağmur']),
  EmojiItem('🌊', 'Dalga', ['wave', 'deniz', 'su', 'dalga']),
  EmojiItem('☀️', 'Güneş', ['sun', 'güneş', 'sıcak', 'yaz', 'hava']),
  EmojiItem('🌤️', 'Az Bulutlu Güneş', ['sun behind small cloud']),
  EmojiItem('⛅', 'Parçalı Bulutlu', ['sun behind cloud']),
  EmojiItem('☁️', 'Bulut', ['cloud', 'bulut']),
  EmojiItem('🌧️', 'Yağmurlu', ['rain', 'yağmur', 'bulut']),
  EmojiItem('⛈️', 'Fırtınalı', ['thunderstorm', 'şimşek', 'yağmur']),
  EmojiItem('❄️', 'Kar Tanesi', ['snowflake', 'kar', 'kış', 'soğuk']),
  EmojiItem('☃️', 'Kardan Adam', ['snowman', 'kar', 'kış']),
  EmojiItem('🌈', 'Gökkuşağı', ['rainbow', 'gökkuşağı', 'renkli']),

  // Food & Drink
  EmojiItem('🍏', 'Yeşil Elma', ['apple', 'elma', 'meyve']),
  EmojiItem('🍎', 'Kırmızı Elma', ['apple', 'elma', 'meyve']),
  EmojiItem('🍐', 'Armut', ['pear', 'armut', 'meyve']),
  EmojiItem('🍊', 'Mandalina', ['tangerine', 'portakal', 'meyve']),
  EmojiItem('🍋', 'Limon', ['lemon', 'limon', 'ekşi']),
  EmojiItem('🍌', 'Muz', ['banana', 'muz', 'meyve']),
  EmojiItem('🍉', 'Karpuz', ['watermelon', 'karpuz', 'meyve', 'yaz']),
  EmojiItem('🍇', 'Üzüm', ['grapes', 'üzüm', 'meyve']),
  EmojiItem('🍓', 'Çilek', ['strawberry', 'çilek', 'meyve']),
  EmojiItem('🍒', 'Kiraz', ['cherries', 'kiraz', 'meyve']),
  EmojiItem('🍑', 'Şeftali', ['peach', 'şeftali', 'meyve']),
  EmojiItem('🍍', 'Ananas', ['pineapple', 'ananas', 'meyve']),
  EmojiItem('🥥', 'Hindistan Cevizi', ['coconut']),
  EmojiItem('🥝', 'Kivi', ['kiwi', 'kivi']),
  EmojiItem('🍅', 'Domates', ['tomato', 'domates', 'sebze']),
  EmojiItem('🥑', 'Avokado', ['avocado', 'avokado']),
  EmojiItem('🍆', 'Patlıcan', ['eggplant', 'patlıcan']),
  EmojiItem('🥕', 'Havuç', ['carrot', 'havuç']),
  EmojiItem('🌽', 'Mısır', ['corn', 'mısır']),
  EmojiItem('🌶️', 'Acı Biber', ['pepper', 'acı', 'biber']),
  EmojiItem('🍞', 'Ekmek', ['bread', 'ekmek', 'fırın']),
  EmojiItem('🥐', 'Kruvasan', ['croissant', 'kruvasan', 'kahvaltı']),
  EmojiItem('🧀', 'Peynir', ['cheese', 'peynir', 'kahvaltı']),
  EmojiItem('🍖', 'Kemikli Et', ['meat on bone', 'et', 'yemek']),
  EmojiItem('🍗', 'Tavuk Budu', ['poultry leg', 'tavuk', 'yemek']),
  EmojiItem('🥩', 'Biftek', ['cut of meat', 'et', 'biftek']),
  EmojiItem('🍔', 'Hamburger', ['hamburger', 'burger', 'fast food']),
  EmojiItem('🍟', 'Patates Kızartması', ['fries', 'patates', 'fast food']),
  EmojiItem('🍕', 'Pizza', ['pizza', 'fast food', 'yemek']),
  EmojiItem('🌭', 'Sosisli', ['hot dog']),
  EmojiItem('🥪', 'Sandviç', ['sandwich', 'sandviç', 'öğle yemeği']),
  EmojiItem('🍳', 'Sahan Yumurta', ['egg', 'yumurta', 'tava', 'kahvaltı']),
  EmojiItem('🍲', 'Sulu Yemek', ['stew', 'yemek', 'çorba']),
  EmojiItem('🥗', 'Salata', ['salad', 'salata', 'sağlıklı', 'diyet']),
  EmojiItem(' popcorn', 'Patlamış Mısır', ['popcorn', 'mısır', 'sinema', 'film']),
  EmojiItem('🍿', 'Patlamış Mısır', ['popcorn', 'mısır', 'sinema']),
  EmojiItem('🍣', 'Suşi', ['sushi', 'suşi', 'japon']),
  EmojiItem('🍦', 'Yumuşak Dondurma', ['ice cream', 'dondurma', 'tatlı']),
  EmojiItem('🍩', 'Donut', ['donut', 'donut', 'tatlı']),
  EmojiItem('🍪', 'Kurabiye', ['cookie', 'kurabiye', 'bisküvi']),
  EmojiItem('🎂', 'Doğum Günü Pastası', ['cake', 'pasta', 'doğum günü', 'kutlama']),
  EmojiItem('🍰', 'Dilim Pasta', ['shortcake', 'pasta', 'tatlı']),
  EmojiItem('🍫', 'Çikolata', ['chocolate', 'çikolata', 'tatlı']),
  EmojiItem('🍬', 'Şeker', ['candy', 'şeker', 'tatlı']),
  EmojiItem('🍭', 'Lolipop', ['lollipop', 'lolipop', 'şeker']),
  EmojiItem('☕', 'Kahve/Çay', ['coffee', 'tea', 'kahve', 'çay', 'sıcak', 'kupa']),
  EmojiItem('🍷', 'Şarap', ['wine', 'şarap', 'içki']),
  EmojiItem('🍻', 'Bira Bardakları', ['clinking beers', 'şerefe', 'bira']),

  // Activities & Sports
  EmojiItem('⚽', 'Futbol', ['soccer', 'football', 'futbol', 'top', 'maç']),
  EmojiItem('🏀', 'Basketbol', ['basketball', 'basketbol', 'top', 'maç']),
  EmojiItem('🎾', 'Tenis', ['tennis', 'tenis', 'raket', 'top']),
  EmojiItem('🏐', 'Voleybol', ['volleyball', 'voleybol', 'top']),
  EmojiItem('🎱', 'Bilardo', ['billiards', 'bilardo', '8 top']),
  EmojiItem('🎯', 'Dart/Hedef', ['dart', 'target', 'hedef', 'isabet', 'amaç', 'odak']),
  EmojiItem('🎮', 'Konsol Oyunu', ['game', 'controller', 'oyun', 'playstation', 'xbox']),
  EmojiItem('🎲', 'Zar', ['dice', 'zar', 'oyun', 'kutu oyunu']),
  EmojiItem('🧩', 'Yapboz', ['puzzle', 'yapboz', 'zeka']),
  EmojiItem('🏃', 'Koşan', ['runner', 'koşu', 'spor', 'koşmak', 'hızlı']),
  EmojiItem('🚴', 'Bisikletçi', ['cyclist', 'bisiklet', 'spor', 'yol']),
  EmojiItem('🧘', 'Yoga/Meditasyon', ['yoga', 'meditation', 'huzur', 'rahatlama', 'odak']),

  // Travel & Places
  EmojiItem('🚗', 'Araba', ['car', 'araba', 'oto', 'yolculuk']),
  EmojiItem('🚕', 'Taksi', ['taxi', 'taksi', 'sarı']),
  EmojiItem('🚌', 'Otobüs', ['bus', 'otobüs', 'toplu taşıma']),
  EmojiItem('🚓', 'Polis Arabası', ['police car', 'polis']),
  EmojiItem('ambulans', 'Ambulans', ['ambulance', 'acil']),
  EmojiItem('🚒', 'İtfaiye', ['fire engine', 'itfaiye', 'yangın']),
  EmojiItem('🚲', 'Bisiklet', ['bicycle', 'bisiklet', 'yol']),
  EmojiItem('🚨', 'Siren', ['siren', 'polis', 'acil', 'alarm']),
  EmojiItem('✈️', 'Uçak', ['airplane', 'plane', 'uçak', 'uçuş', 'seyahat', 'tatil']),
  EmojiItem('🚀', 'Roket', ['rocket', 'roket', 'uzay', 'hızlı', 'yükseliş']),
  EmojiItem('🚢', 'Gemi', ['ship', 'gemi', 'deniz']),
  EmojiItem('🏖️', 'Plaj/Şemsiye', ['beach', 'plaj', 'deniz', 'kum', 'tatil', 'yaz']),
  EmojiItem('🏠', 'Ev', ['house', 'ev', 'konut', 'aile', 'yaşam']),
  EmojiItem('🏢', 'Ofis Binası', ['office', 'ofis', 'iş', 'şirket', 'bina']),
  EmojiItem('🏫', 'Okul', ['school', 'okul', 'eğitim', 'öğrenci']),
  EmojiItem('🏥', 'Hastane', ['hospital', 'hastane', 'doktor', 'sağlık']),
  EmojiItem('🏦', 'Banka', ['bank', 'banka', 'para']),
  EmojiItem('🕌', 'Cami', ['mosque', 'cami', 'ibadet', 'namaz']),

  // Objects & Work
  EmojiItem('💼', 'Evrak Çantası', ['briefcase', 'iş', 'çanta', 'toplantı', 'ofis', 'mesai']),
  EmojiItem('🎒', 'Okul Çantası', ['backpack', 'çanta', 'okul', 'seyahat']),
  EmojiItem('👓', 'Gözlük', ['glasses', 'gözlük', 'okuma']),
  EmojiItem('💻', 'Dizüstü Bilgisayar', ['laptop', 'bilgisayar', 'pc', 'yazılım', 'çalışma', 'ofis']),
  EmojiItem('⏰', 'Çalar Saat', ['alarm clock', 'saat', 'alarm', 'zaman', 'sabah']),
  EmojiItem('⏳', 'Kum Saati', ['hourglass', 'saat', 'zaman', 'süre']),
  EmojiItem('💡', 'Ampul/Fikir', ['bulb', 'ampul', 'fikir', 'buluş', 'yaratıcı']),
  EmojiItem('💸', 'Kanatlı Para', ['money with wings', 'para', 'gitti']),
  EmojiItem('💵', 'Dolar Banknotu', ['dollar bill', 'para', 'nakit']),
  EmojiItem('💰', 'Para Torbası', ['money bag', 'para', 'zengin', 'bütçe']),
  EmojiItem('💳', 'Kredi Kartı', ['credit card', 'kart', 'ödeme', 'banka']),
  EmojiItem('💎', 'Elmas', ['gem', 'elmas', 'değerli', 'mücevher']),
  EmojiItem('🔧', 'İngiliz Anahtarı', ['wrench', 'anahtar', 'tamir', 'araç']),
  EmojiItem('⚙️', 'Dişli', ['gear', 'ayarlar', 'dişli', 'çark']),
  EmojiItem('📦', 'Kutu/Paket', ['box', 'kutu', 'kargo', 'sipariş']),
  EmojiItem('✉️', 'Zarf', ['envelope', 'zarf', 'mektup', 'posta', 'mail']),
  EmojiItem('📝', 'Not/Kalem', ['memo', 'not', 'yazı', 'kalem', 'defter']),
  EmojiItem('📌', 'Raptiye', ['pushpin', 'raptiye', 'sabitlendi', 'not']),
  EmojiItem('🔔', 'Zil/Bildirim', ['bell', 'zil', 'bildirim', 'alarm', 'hatırlatıcı']),
  EmojiItem('🎨', 'Boya Paleti', ['palette', 'resim', 'sanat', 'renk', 'çizim']),
  EmojiItem('🎬', 'Klaket', ['clapperboard', 'film', 'sinema', 'video']),
  EmojiItem('🧿', 'Nazar Boncuğu', ['nazar amulet', 'nazar', 'mavi', 'şans']),

  // Symbols
  EmojiItem('⭐', 'Yıldız', ['star', 'yıldız', 'favori', 'puan']),
  EmojiItem('🌟', 'Pırıl Pırıl Yıldız', ['glowing star', 'parlak', 'harika']),
  EmojiItem('✨', 'Parıltılar', ['sparkles', 'yeni', 'temiz', 'parlak']),
  EmojiItem('⚡', 'Yüksek Voltaj', ['lightning', 'elektrik', 'hızlı', 'şarj', 'enerji']),
  EmojiItem('🎈', 'Balon', ['balloon', 'balon', 'parti', 'kutlama']),
  EmojiItem('🎉', 'Konfeti Patlaması', ['tada', 'celebration', 'kutlama', 'tebrik', 'yaşasın', 'parti']),
  EmojiItem('🎁', 'Hediye', ['gift', 'present', 'hediye', 'sürpriz', 'doğum günü']),
  EmojiItem('🏆', 'Kupa', ['trophy', 'kupa', 'şampiyon', 'kazanan', 'başarı', 'ödül']),
];

List<EmojiItem> searchEmojis(String query) {
  if (query.trim().isEmpty) {
    return emojiDatabase;
  }
  final lowerQuery = query.toLowerCase().trim();
  return emojiDatabase.where((item) {
    if (item.name.toLowerCase().contains(lowerQuery)) return true;
    for (var kw in item.keywords) {
      if (kw.toLowerCase().contains(lowerQuery)) return true;
    }
    return false;
  }).toList();
}
